import { access, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { CaatingaError, CaatingaErrorCode } from "../errors/CaatingaError.js";

const BUNDLER_ENTRY = "./src/index.ts";
export const ROOT_BINDING_INDEX_CONTENT = 'export * from "./src/index.js";\n';

// Self-contained browser polyfill shipped inside every generated binding.
// `@stellar/stellar-sdk` and the wallet kit expect Node's `Buffer` global,
// which browsers don't provide — so an app that merely imports a binding would
// otherwise crash with "Buffer is not defined" when connecting or signing.
// Importing the binding sets it up; it's a no-op in Node, where Buffer exists.
export const POLYFILLS_FILENAME = "caatinga-polyfills.ts";
export const POLYFILLS_IMPORT_LINE = 'import "./caatinga-polyfills.js";';
export const POLYFILLS_CONTENT = `// Generated by Caatinga — do not edit.
//
// @stellar/stellar-sdk and @creit.tech/stellar-wallets-kit expect Node's
// \`Buffer\` global, which browsers don't provide. Importing this binding sets
// it up so the app doesn't crash with "Buffer is not defined" when signing or
// connecting a wallet. No-op in Node, where Buffer already exists.
import { Buffer } from "buffer";

// Typed view of globalThis so the assignment doesn't depend on @types/node's
// global Buffer typing being present in the consuming app.
const globalScope = globalThis as typeof globalThis & { Buffer?: typeof Buffer };

if (typeof globalScope.Buffer === "undefined") {
  globalScope.Buffer = Buffer;
}
`;

type BindingPackageJson = {
  main?: string;
  types?: string;
  exports?: Record<string, unknown>;
  [key: string]: unknown;
};

function resolveExportEntry(exportsField: Record<string, unknown> | undefined): string | undefined {
  if (!exportsField) {
    return undefined;
  }

  const rootExport = exportsField["."];
  if (typeof rootExport === "string") {
    return rootExport;
  }

  if (rootExport && typeof rootExport === "object" && !Array.isArray(rootExport)) {
    const conditions = rootExport as Record<string, unknown>;
    for (const key of ["import", "default", "types"]) {
      const value = conditions[key];
      if (typeof value === "string") {
        return value;
      }
    }
  }

  return undefined;
}

function pointsToDist(main: string | undefined): boolean {
  return typeof main === "string" && main.replace(/^\.\//, "").startsWith("dist/");
}

function pointsToBundlerSource(entry: string | undefined): boolean {
  return entry === BUNDLER_ENTRY || entry === "./src/index.js";
}

function shouldPatchPackageJson(packageJson: BindingPackageJson): boolean {
  const exportEntry = resolveExportEntry(
    typeof packageJson.exports === "object" && packageJson.exports !== null && !Array.isArray(packageJson.exports)
      ? (packageJson.exports as Record<string, unknown>)
      : undefined
  );

  return (
    pointsToDist(packageJson.main) ||
    pointsToDist(packageJson.types) ||
    !pointsToBundlerSource(exportEntry)
  );
}

async function ensureBufferPolyfill(outputDir: string): Promise<void> {
  const srcDir = path.join(outputDir, "src");
  const polyfillPath = path.join(srcDir, POLYFILLS_FILENAME);
  const entryPath = path.join(srcDir, "index.ts");

  // Caatinga owns this file — keep it current on every regenerate.
  await writeFile(polyfillPath, POLYFILLS_CONTENT, "utf8");

  const entry = await readFile(entryPath, "utf8");
  if (entry.includes(POLYFILLS_IMPORT_LINE)) {
    return;
  }

  // Prepend so the polyfill module is evaluated before "./client.js" (and the
  // @stellar/stellar-sdk it pulls in) — ES import order is top-to-bottom.
  await writeFile(entryPath, `${POLYFILLS_IMPORT_LINE}\n${entry}`, "utf8");
}

// @stellar/stellar-sdk generate emits error enums as a value only
// (`export const Name = { 1: { message: "..." } }`), never as a type. Any
// binding that uses `Result<T, Name>` then fails with TS2749 ("'Name' refers
// to a value, but is being used as a type here") because Result's error
// param requires `{ message: string }`. Declaration merging a matching
// `interface` fixes this without touching the generated runtime value.
const ERROR_ENUM_CONST_PATTERN = /export const (\w+) = \{[\s\S]*?\n\}/g;

async function ensureErrorEnumInterfaces(outputDir: string): Promise<void> {
  const typesPath = path.join(outputDir, "src", "types.ts");

  let content: string;
  try {
    content = await readFile(typesPath, "utf8");
  } catch {
    return;
  }

  let patched = content;
  let insertedLength = 0;

  for (const match of content.matchAll(ERROR_ENUM_CONST_PATTERN)) {
    const [block, name] = match;
    if (content.includes(`export interface ${name} {`)) {
      continue;
    }

    const insertAt = (match.index ?? 0) + block.length + insertedLength;
    const interfaceDecl = `\n\nexport interface ${name} {\n  message: string;\n}`;
    patched = `${patched.slice(0, insertAt)}${interfaceDecl}${patched.slice(insertAt)}`;
    insertedLength += interfaceDecl.length;
  }

  if (patched !== content) {
    await writeFile(typesPath, patched, "utf8");
  }
}

// @stellar/stellar-sdk generate only adds `Address` to types.ts's import from
// '@stellar/stellar-sdk' when some field type needs it — but that field can
// end up unused in the final output for some contracts, leaving a dangling
// import that trips no-unused-vars. Only strip it when "Address" truly
// doesn't appear anywhere else in the file, so a real usage is never removed.
const STELLAR_SDK_IMPORT_PATTERN = /^import \{([^}]*)\} from '@stellar\/stellar-sdk';$/m;

async function pruneUnusedAddressImport(outputDir: string): Promise<void> {
  const typesPath = path.join(outputDir, "src", "types.ts");

  let content: string;
  try {
    content = await readFile(typesPath, "utf8");
  } catch {
    return;
  }

  const match = content.match(STELLAR_SDK_IMPORT_PATTERN);
  if (!match) {
    return;
  }

  const [importLine, importList] = match;
  const names = importList.split(",").map((entry) => entry.trim()).filter(Boolean);
  if (!names.includes("Address")) {
    return;
  }

  const importStart = match.index ?? 0;
  const withoutImportLine = content.slice(0, importStart) + content.slice(importStart + importLine.length);
  if (withoutImportLine.includes("Address")) {
    return;
  }

  const remaining = names.filter((entry) => entry !== "Address");
  const replacement =
    remaining.length > 0 ? `import {${remaining.join(", ")}} from '@stellar/stellar-sdk';` : "";

  const patched =
    replacement.length > 0
      ? `${content.slice(0, importStart)}${replacement}${content.slice(importStart + importLine.length)}`
      : `${content.slice(0, importStart)}${content.slice(importStart + importLine.length)}`.replace(
          /\n\n\n/,
          "\n\n"
        );

  await writeFile(typesPath, patched, "utf8");
}

// @stellar/stellar-sdk generate always emits `Client` as both an interface
// (typed method signatures) and a class extending ContractClient (which
// dispatches those methods through a Proxy at runtime) — intentional
// declaration merging that eslint's no-unsafe-declaration-merging flags as if
// it were a mistake. Silence it at the two fixed spots instead of asking every
// consuming project to disable the rule project-wide.
const CLIENT_DECLARATION_MERGING_TARGETS = ["export interface Client {", "export class Client extends ContractClient {"];
const ESLINT_DISABLE_DECLARATION_MERGING =
  "// eslint-disable-next-line @typescript-eslint/no-unsafe-declaration-merging -- intentional: Client is both the typed interface and the ContractClient subclass that dispatches its methods via Proxy.";

async function ensureClientDeclarationMergingComments(outputDir: string): Promise<void> {
  const clientPath = path.join(outputDir, "src", "client.ts");

  let content: string;
  try {
    content = await readFile(clientPath, "utf8");
  } catch {
    return;
  }

  let patched = content;
  for (const target of CLIENT_DECLARATION_MERGING_TARGETS) {
    const marker = `${ESLINT_DISABLE_DECLARATION_MERGING}\n${target}`;
    if (!patched.includes(target) || patched.includes(marker)) {
      continue;
    }
    patched = patched.replace(target, marker);
  }

  if (patched !== content) {
    await writeFile(clientPath, patched, "utf8");
  }
}

async function ensureRootBindingIndex(outputDir: string): Promise<void> {
  const rootIndexPath = path.join(outputDir, "index.ts");

  try {
    // Any existing root index is preserved (whether Caatinga-authored or a
    // non-Caatinga one the generator might start shipping); only an absent
    // file is created.
    await readFile(rootIndexPath, "utf8");
    return;
  } catch {
    await writeFile(rootIndexPath, ROOT_BINDING_INDEX_CONTENT, "utf8");
  }
}

export async function patchGeneratedBindingPackage(outputDir: string): Promise<void> {
  const packageJsonPath = path.join(outputDir, "package.json");
  const entryPath = path.join(outputDir, "src", "index.ts");

  try {
    await access(entryPath);
  } catch {
    throw new CaatingaError(
      "Generated binding package is missing src/index.ts.",
      CaatingaErrorCode.BINDINGS_FAILED,
      "Re-run ctg generate or check @stellar/stellar-sdk generate output."
    );
  }

  let raw: string;
  try {
    raw = await readFile(packageJsonPath, "utf8");
  } catch {
    throw new CaatingaError(
      "Generated binding package is missing package.json.",
      CaatingaErrorCode.BINDINGS_FAILED,
      "Re-run ctg generate or check @stellar/stellar-sdk generate output."
    );
  }

  let packageJson: BindingPackageJson;
  try {
    packageJson = JSON.parse(raw) as BindingPackageJson;
  } catch {
    throw new CaatingaError(
      "Generated binding package.json is not valid JSON.",
      CaatingaErrorCode.BINDINGS_FAILED,
      "Re-run ctg generate or check @stellar/stellar-sdk generate output."
    );
  }

  if (shouldPatchPackageJson(packageJson)) {
    packageJson.main = BUNDLER_ENTRY;
    packageJson.types = BUNDLER_ENTRY;
    packageJson.exports = {
      ...(typeof packageJson.exports === "object" && packageJson.exports !== null && !Array.isArray(packageJson.exports)
        ? packageJson.exports
        : {}),
      ".": BUNDLER_ENTRY,
    };

    await writeFile(packageJsonPath, `${JSON.stringify(packageJson, null, 2)}\n`, "utf8");
  }

  await ensureBufferPolyfill(outputDir);
  await ensureRootBindingIndex(outputDir);
  await ensureErrorEnumInterfaces(outputDir);
  await pruneUnusedAddressImport(outputDir);
  await ensureClientDeclarationMergingComments(outputDir);
}
